### PR TITLE
CHET-128: Implement alternative state management strategy

### PR DESCRIPTION
**Pull request by bpar476**
This is the alternative strategy outlined in: #29 

> I think perhaps it would be best to leave the state pattern behind and try to avoid such a generic approach. Instead of the entire process being managed by a StateMachineService, each component of the migration is managed by its own service (i.e. our current implementation). This would be backed up by a very lightweight state management system which exists purely to ensure all actions are taken in the correct order.
Consider the previous example with this different architecture.

    The user has filled out the quick start form
    User clicks "Deploy"
    UI calls out to QuickStartService and requests to provision a new stack
    The QuickStartService checks the MigrationState is equal to STACK_FORM (the only state where a quick start can be deployed)
    The QuickStartService initiates deployment.
    The QuickStartService sets the MigrationState to STACK_DEPLOY
    The request from (3) returns
    The UI goes to the next page: waiting for the stack to finish deploying
    The UI polls the stack status from the backend until the migration is complete
    Once the migration is completed, the backend sets its state to MIGRATION_STACK_DEPLOY

> The downside of this approach is that the state machine is less strictly enforced. Services have to check with the state machine that they can run rather than the state machine calling the services when it is their turn.
The benefit is each service is completely independent of the others. It doesn't matter what the implementation of each stage of the migration is, it only matters that there is an implementation for that state. There is no enforcing on when a state transition can occur (either automatically or by user action).

### CODE REVIEW

**Comment by bpar476** [comment]
This is not intended to be merged, it has no tests and hasn't even been executed. It serves as a demonstration of a state implementation.

**Comment by tarka** [comment]
This seem like a better approach; I'd prefer the simplest possible thing that works. At this point we should assume that anything we do will be heavily changed over the course of development, so we shouldn't get too bogged down in abstract structures and patterns.

**Comment by nanux** [comment]
As commented in the channel, I like flexibility and lower overhead of this approach. Each of the stage is responsible to surface the restrictions under which it can run. I just wonder if we should provide a "dry run" validation method. This method will be used in the actual run of the stage but it also allows consumers to validate whether the stage can be transition into without actually running it (might be useful for frontend). But maybe it is also in the bucket with other YAGNI.

```
public StageReport runStage() {
     if (!isValid()) {
        throws new InvalidTransition()
     }
     runstage...
}

public boolean isValid() {
      validatePrerequisites()
}
```

**Comment by bpar476** [comment]
Closing because this was a demonstration PR

**Pull request closed without merging**
