### PR TITLE
CHET-196: Add editorconfig and format the files for consistency

### PR DESCRIPTION
**Pull request by nanux**
- The .editorconfig settings is the default IDEA configuration
- Run formatting across java files
- Optimize imports in java files

### CODE REVIEW

**Comment by theghostwhoforks** [comment]
LGTM. Btw, how is this commit ready to merge before any approvals? 🤔

**Comment by nanux** [comment]
> LGTM. Btw, how is this commit ready to merge before any approvals? 🤔

I am not sure, strange.

**Comment by bpar476** [comment]
Is there some way we can add this in CI?

**Comment by bpar476** [comment]
Misclick 😢

**Comment by nanux** [comment]
> Is there some way we can add this in CI?

You mean the check that everything is formatted or that it will format the code automatically? I am usually trying to avoid code editing by CI on the same branch as development is happening as it might complicate dev flow with a merge conflict. I will check if we can introduce CI check that everything is formatted.

**Comment by nanux** [comment]
There is a https://github.com/marketplace/actions/editorconfig-action but it is currently broken due to https://github.com/zbeekman/EditorConfig-Action/issues/35 - I've subscribed for now and we can revisit it later if we hit issues with editor config issues.

**Pull request merged**
