### PR TITLE
Chet 408 fix supplier imports

### PR DESCRIPTION
**Pull request by theghostwhoforks**
Use java util supplier, as used by `LazyReference` class from `io.atlassian.concurrent` libraries

### CODE REVIEW

**Comment by theghostwhoforks** [comment]
I've verified that the OSGI integration works as expected with this chagne

**Comment by bpar476** [comment]
Does the disabled test passs?

**Comment by nanux** [comment]
> I've verified that the OSGI integration works as expected with this chagne

Was there any benefit by using the Atlassian package?

**Comment by theghostwhoforks** [comment]
> Does the disabled test passs?

it does - this is done in the other PR #207

**Comment by theghostwhoforks** [comment]
> > I've verified that the OSGI integration works as expected with this chagne
> 
> Was there any benefit by using the Atlassian package?

Nothing as far as I could tell. I think the atlassian package had the function definition before it landed in java 8.

io.atlassian.util library defers to using the java definition and not the homegrown one

**Pull request merged**
