### PR TITLE
DCD-1162: Resolve a bunch of frontend vulnerabilities by upgrading packages

### PR DESCRIPTION
**Pull request by bpar476**
This resolves 10 of the 11 [dependabot alerts](https://github.com/atlassian-labs/dc-migration-assistant/security/dependabot).

Vulnerable package | Source | Severity | Impact | Action
-- | -- | -- | -- | --
http-proxy https://github.com/atlassian-labs/dc-migration-assistant/security/dependabot/yarn.lock/http-proxy/open | Transitive dependency of webpack-dev-server in frontendmodule yarn.lock | High severity - Denial of service | Needs investigating - webpack-dev-server is only run locally for developers to test the frontend without running Jira. | Patch webpack-dev-server to 3.11
immerhttps://github.com/atlassian-labs/dc-migration-assistant/security/dependabot/yarn.lock/immer/open | Transitive dependency of react-scripts in frontend module yarn.lock | HIGH SEVerity - Prototype pollution | Needs investigating - react-scripts is used by “Create React App” to handle building and running the React application. i.e. react-scripts start | PATCH react-scripts to 4.0.3  and storybook/react to 6.1.20
serialize-javascripthttps://github.com/atlassian-labs/dc-migration-assistant/security/dependabot/yarn.lock/serialize-javascript/open | Transitive dependency of react-scripts and storybook →  terser-webpack-plugin → serialize-javascript | high severity - Allows arbitrary code injection | needs investigating - It looks like this is only used as part of the build for storybook and react-scripts. | PATCH react-scripts to 4.0.3  and storybook/react to 6.1.20
elliptichttps://github.com/atlassian-labs/dc-migration-assistant/security/dependabot/yarn.lock/elliptic/open | Transitive dependency. webpack →  node-libs-browser → create-ecdh → elliptic | high severity | Needs investigating - webpack only run to build the bundle. | Patch webpack-dev-server to 3.11
node-forgehttps://github.com/atlassian-labs/dc-migration-assistant/security/dependabot/yarn.lock/node-forge/open | Transitive dependencywebpack-dev-server → selfsigned → node-forge | HIGH SEVerity - Prototype pollution | Needs investigating - webpack-dev-server is only run locally for developers to test the frontend without running Jira. | Patch webpack-dev-server to 3.11
node-notifierhttps://github.com/atlassian-labs/dc-migration-assistant/security/dependabot/yarn.lock/node-notifier/open | Transitive dependencyjest/cli → jest/core → jest/reporters → node-notifier | medium - It allows an attacker to run arbitrary commands on Linux machines due to the options params not being sanitised when being passed an array. | needs investigating - Jest is used for frontend tests | PATCH jest to 26.6.3
inihttps://github.com/atlassian-labs/dc-migration-assistant/security/dependabot/jira-e2e-tests/cypress/yarn.lock/ini/open | Transitive dependencyreact-scripts → react-dev-utils → global-modules → global-prefix → ini | HIGH SEVerity - Prototype pollution | Needs investigating - react-scripts is used by “Create React App” to handle building and running the React application. i.e. react-scripts start | Run a yarn upgrade which updates in resolution to 1.3.8
lodashhttps://github.com/atlassian-labs/dc-migration-assistant/security/dependabot/yarn.lock/lodash/open | Transitive dependencyjest-cli → jest-config →jest-environment-jsdom → jsdom → request-promise-native → request-promise-core → lodash | HIGH SEVerity - Prototype pollution | NEEDS investigating - Jest is used for frontend tests | PATCH jest to 26.6.3
node-fetchhttps://github.com/atlassian-labs/dc-migration-assistant/security/dependabot/yarn.lock/node-fetch/open | Transitive dependency of storybook-core, isomorphic-fetch, and cross-fetch | LOW - Does not honour size after following redirect, can result in crashes | NEEDs investigating - It is a transitive dependency of styled-components through fbjs → cross-fetch/isomorphic-fetch however we aren’t using it directly. | Not able to update styled-components as @atlaskit components depend on an older version of styled-components.

---

I'm doing a manual test myself to make sure everything looks okay and will upload a zip archive with screenshots of most pages. So far I have only noticed one issue. There is a weird border surrounding the cursor for certain text input fields. I believe this came from AUI 9 upgrade (I saw a similar issue in a Confluence innovation week project).

### CODE REVIEW

**Comment by bpar476** [comment]
Here is a zipfile with the screenshots. You can see the text border I was talking about in the region-select page screenshot.

The last screenshot with the bobblehead is on the destination instance demonstrating that the database and files migrated successfully.
 
[DCMAFrontendWithPackageUpdatesScreenshots.zip](https://github.com/atlassian-labs/dc-migration-assistant/files/6072868/DCMAFrontendWithPackageUpdatesScreenshots.zip)

**Comment by nanux** [comment]
I think we can merge as it is but can we ask the AUI team whether they know about the border around the form fields and if we can remove it somehow? Maybe we are not using the components correctly now.

**Review by nanux — APPROVED** [review]

**Comment by bpar476** [comment]
> I think we can merge as it is but can we ask the AUI team whether they know about the border around the form fields and if we can remove it somehow? Maybe we are not using the components correctly now.

I'm trying to get the app running in storybook to confirm if it's AUI. Will let you know, looks like storybook broke during the upgrade.

**Comment by bpar476** [comment]
Confirmed that it's not happening in storybook so I've reached out to the frontend platform team.

**Comment by bpar476** [comment]
We can fix the outline with this css:

```
    input:focus-visible {
        box-shadow: none;
    }
```

frontend platform will release a new version of AUI that doesn't have the issue but we still need the css hack to resolve the issue for older versions.

**Pull request merged**
